name = "Community Developer Tools"
author = "DartRuffian"
prefix = "cdt"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_cdt.png",
    "logo_cdt_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "DartRuffian"